apiVersion: v1
kind: Pod
metadata:
    name: pod-python
    labels:
      app: python-pod 
spec:
    containers:
        - name: container-python
          image: webapp2:latest
          imagePullPolicy: Never #to run images on local disk
          ports:
            - containerPort: 80